import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={styles.main}>
        <div style={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code style={styles.code}>pages/index.tsx</code>
          </p>
        </div>

        <div style={styles.center}>
          <h1 style={styles.title}>
            Welcome to <span style={styles.highlight}>Next.js!</span>
          </h1>
        </div>

        <div style={styles.grid}>
          <a
            href="https://nextjs.org/docs"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>→</span>
            </h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://nextjs.org/learn"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>→</span>
            </h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>→</span>
            </h2>
            <p>Explore starter templates for Next.js.</p>
          </a>

          <a
            href="https://vercel.com/new"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>→</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}

const styles = {
  main: {
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '6rem',
    minHeight: '100vh',
    fontFamily: 'system-ui, sans-serif',
    backgroundColor: '#000',
    color: '#fff',
  },
  description: {
    display: 'inherit',
    justifyContent: 'inherit',
    alignItems: 'inherit',
    fontSize: '0.85rem',
    maxWidth: 'var(--max-width)',
    width: '100%',
    zIndex: 2,
  },
  code: {
    fontWeight: 700,
    fontFamily: 'monospace',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: '0.3rem 0.5rem',
    borderRadius: '5px',
  },
  center: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative' as const,
    padding: '4rem 0',
  },
  title: {
    fontSize: '3.5rem',
    fontWeight: 700,
    lineHeight: 1.2,
    textAlign: 'center' as const,
    margin: 0,
  },
  highlight: {
    background: 'linear-gradient(to right, #0070f3, #00d4ff)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    width: '100%',
    maxWidth: '1000px',
    gap: '1rem',
  },
  card: {
    padding: '1rem 1.2rem',
    borderRadius: '10px',
    background: 'rgba(255, 255, 255, 0.05)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    transition: 'background 200ms, border 200ms',
    textDecoration: 'none',
    color: 'inherit',
  },
}
